sonar.projectKey=JeanPiere91_tours-booking-platform
sonar.organization=jeanpiere91
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src
sonar.tests=backend/__tests__

sonar.exclusions=node_modules/**,coverage/**

sonar.projectName=Tours Booking Platform
sonar.sourceEncoding=UTF-8